create view V_SALARIATI as
select A.EMPLOYEE_ID,A.FIRST_NAME,A.LAST_NAME,A.JOB_ID,B.JOB_TITLE,A.DEPARTMENT_ID,C.DEPARTMENT_NAME,A.SALARY,A.COMMISSION_PCT
from EMPLOYEES A,JOBS B,DEPARTMENTS C 
WHERE A.JOB_ID=B.JOB_ID AND A.DEPARTMENT_ID=C.DEPARTMENT_ID;

COMMIT

CREATE OR REPLACE VIEW V_SALARIATI_FINANCE AS
SELECT * FROM EMPLOYEES A
WHERE A.DEPARTMENT_ID=100
--WITH CHECK OPTION;

SELECT * FROM V_SALARIATI_FINANCE;

INSERT INTO V_SALARIATI_FINANCE(EMPLOYEE_ID,EMAIL,LAST_NAME,JOB_ID,HIRE_DATE,DEPARTMENT_ID)
VALUES (SECVENTA1.NEXTVAL,'AND@YAAHO','111aDD','AD_VP',SYSDATE,100);

COMMIT

CREATE SEQUENCE SECVENTA1
INCREMENT BY 1
START WITH 2207

ALTER SEQUENCE SECVENTA2
--INCREMENT BY 10   
--START WITH 10
--MAXVALUE 1000
--CACHE 100
CYCLE;

SELECT SECVENTA2.CURRVAL,SECVENTA2.NEXTVAL FROM DUAL

SELECT * FROM DUAL












