select LAST_NAME,HIRE_DATE
from EMPLOYEES where DEPARTMENT_ID =
  (select DEPARTMENT_ID from EMPLOYEES
  where LAST_NAME = 'Zlotkey') and 
  LAST_NAME NOT LIKE &r
  ;

-- EX 2
SELECT LAST_NAME,DEPARTMENT_ID 
FROM EMPLOYEES B
WHERE B.DEPARTMENT_ID IN
(SELECT A.DEPARTMENT_ID 
FROM EMPLOYEES  A
WHERE A.LAST_NAME LIKE '%u%');


-- EX 3
SELECT A.LAST_NAME,A.JOB_ID,A.SALARY
FROM EMPLOYEES A
WHERE A.JOB_ID IN ( SELECT B.JOB_ID
                    FROM JOBS B 
                    WHERE B.JOB_TITLE LIKE 'P%') AND A.SALARY NOT IN(2500,3500,7000) 
ORDER BY A.JOB_ID ASC, A.LAST_NAME DESC ;

-- EX 4

--ANGAJATII CARE CASTIGA MAI MULT DECAT ORICE ANGAJAT DIN DEP 30
SELECT A.LAST_NAME,A.SALARY
FROM EMPLOYEES A
WHERE A.SALARY > ANY (SELECT B.SALARY
                      FROM EMPLOYEES B WHERE B.DEPARTMENT_ID=30);

SELECT * FROM EMPLOYEES A
WHERE A.EMPLOYEE_ID=2206
--1107

INSERT INTO EMPLOYEES (EMPLOYEE_ID, FIRST_NAME,LAST_NAME, HIRE_DATE,EMAIL,JOB_ID,SALARY,COMMISSION_PCT) 
VALUES ((SELECT MAX(EMPLOYEE_ID)+1000 FROM EMPLOYEES), 'APOSTOIU','Andrei ', sysdate,'A@MAIL','IT_PROG',10000,0.2);

COMMIT

UPDATE EMPLOYEES A
SET A.DEPARTMENT_ID=(SELECT B.DEPARTMENT_ID FROM DEPARTMENTS B WHERE DEPARTMENT_NAME LIKE 'IT')
WHERE A.EMPLOYEE_ID=2206
;











